---
# handlers file for while_true_do.sys_auto_update

- name: Restart auto_update Service
  service:
    name: "{{ wtd_sys_auto_update_service }}"
    state: "restarted"
  become: true
  tags:
    - auto_update
    - configuration
    - service
    - update
